artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: "https://github.com/Shwetagithub24/ML-Project-with-MLFlow-and-AWS-EC2/raw/refs/heads/main/data.zip"
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    unzip_data_dir: C:\Users\shwet\Documents\CV and applications\Projects\ML Project with MLFlow and AWS EC2\ML-Project-with-MLFlow-and-AWS-EC2\artifacts\data_ingestion\data\winequality-red.csv
    STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
    root_dir: artifacts/data_transformation
    data_path: C:\Users\shwet\Documents\CV and applications\Projects\ML Project with MLFlow and AWS EC2\ML-Project-with-MLFlow-and-AWS-EC2\artifacts\data_ingestion\data\winequality-red.csv

model_trainer:
    root_dir: artifacts/model_trainer
    train_data_path: C:\Users\shwet\Documents\CV and applications\Projects\ML Project with MLFlow and AWS EC2\artifacts\data_transformation\train.csv
    test_data_path: C:\Users\shwet\Documents\CV and applications\Projects\ML Project with MLFlow and AWS EC2\artifacts\data_transformation\test.csv
    model_name: model.joblib




model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: C:\Users\shwet\Documents\CV and applications\Projects\ML Project with MLFlow and AWS EC2\ML-Project-with-MLFlow-and-AWS-EC2\artifacts\data_transformation\test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

